FROM tomcat:8.0.36-jre8
RUN rm -rf /usr/local/tomcat/webapps/*
#RUN wget -q -O /usr/local/tomcat/webapps/ROOT.war http://rap.taobao.org/release/RAP-0.14.1-SNAPSHOT.war
RUN wget -q -O /usr/local/tomcat/webapps/ROOT.war http://192.168.7.110/Rap.war
